### ISSUE TITLE
Error attempting to install Plugin

### ISSUE THREAD

**Issue by markarupert** [litehelpers/Cordova-sqlite-evcore-extbuild-free#13]
I am getting an error when I try to install the plugin.

C:\Users\Mark\WebstormProjects\sen>cordova plugin add cordova-sqlite-evcore-extbuild-free --save
Error: Cannot find plugin.xml for plugin "cordova-sqlite-evcore-extbuild-free". Please try adding it again.

**Comment by brodybits** [comment]
I have never seen this error. Please show the results of the following:
- cordova plugin ls
- cordova platform ls

I suggest you try this with a fresh new project.

**Comment by markarupert** [comment]
I found it. I had installed it earlier and the plugin remove did not clean it up. I deleted the old folders in the Plugins directory and now it installed.
