### ISSUE TITLE
Creating Indexes

### ISSUE THREAD

**Issue by markarupert** [litehelpers/Cordova-sqlite-evcore-extbuild-free#14]
Can indexes be created with this plugin? I got an error trying to create the following index for my table

CREATE INDEX timeStatusElogIdx ON elog (starttime, endtime, status)

**Comment by brodybits** [comment]
This should be possible though I have not tested this functionality. It would be great if you can show a small test program that demonstrates the problem. A couple bonus items:
- Would you get the same result on the standard cordova-sqlite-storage version?
- What would happen if you bypass the plugin by doing the same thing on the database object returned by window.openDatabase?

**Comment by markarupert** [comment]
It worked fine on the cordova-sqlite-storage version. When I moved to this one is when I got the error.

I will give the database object a try and let you know.

**Comment by markarupert** [comment]
This did not give me an error:

```
                    db.executeSql("CREATE INDEX IF NOT EXISTS timeStatusElogIdx ON elog (starttime, endtime, status)", [], function (results) {
                        deviceLog("CREATE INDEX timeStatusElogIdx success", function (str) {console.log(str)});
                    }, function (err) {
                        deviceLog("CREATE INDEX timeStatusElogIdx Failed, err=" + err.message, function (str) {console.log(str)});
                    });
```

**Comment by brodybits** [comment]
Closing for now. Please report here or in a new issue if you have an error reproduction scenario.
