### ISSUE TITLE
Newbie:  build log reported depricated  API

### ISSUE THREAD

**Issue by bakerjay06074** [litehelpers/Cordova-sqlite-evcore-extbuild-free#16]
I'm a hobbyist working on my first phonegap build project, and I got a depricated API message when trying to use this plugin.  The culprit seems to be /project/src/io/sqlc/SQLiteAndroidDatabase.java.  I'm not sure if this is a real a problem, but here's my build log for your review just in case.

Build Date: 2017-01-03 02:18:26 +0000
--------------------------------------------------------------------------------
PLUGIN OUTPUT
--------------------------------------------------------------------------------
Fetching plugin "https://github.com/litehelpers/Cordova-sqlite-evcore-extbuild-free.git" via git clone
Using shallow clone
Repository "https://github.com/litehelpers/Cordova-sqlite-evcore-extbuild-free.git" checked out to git ref "master" at "1186a7e".
Installing "cordova-sqlite-evcore-extbuild-free" at "0.8.4" for android
--------------------------------------------------------------------------------
COMPILE OUTPUT
--------------------------------------------------------------------------------
Configuration on demand is an incubating feature.
Incremental java compilation is an incubating feature.
:preBuild UP-TO-DATE
:preDebugBuild UP-TO-DATE
:checkDebugManifest
:CordovaLib:preBuild UP-TO-DATE
:CordovaLib:preDebugBuild UP-TO-DATE
:CordovaLib:compileDebugNdk UP-TO-DATE
:CordovaLib:compileLint
:CordovaLib:copyDebugLint UP-TO-DATE
:CordovaLib:mergeDebugProguardFiles
:CordovaLib:packageDebugRenderscript UP-TO-DATE
:CordovaLib:checkDebugManifest
:CordovaLib:prepareDebugDependencies
:CordovaLib:compileDebugRenderscript
:CordovaLib:generateDebugResValues
:CordovaLib:generateDebugResources
:CordovaLib:packageDebugResources
:CordovaLib:compileDebugAidl
:CordovaLib:generateDebugBuildConfig
:CordovaLib:mergeDebugShaders
:CordovaLib:compileDebugShaders
:CordovaLib:generateDebugAssets
:CordovaLib:mergeDebugAssets
:CordovaLib:processDebugManifest
:CordovaLib:processDebugResources
:CordovaLib:generateDebugSources
:CordovaLib:incrementalDebugJavaCompilationSafeguard
:CordovaLib:compileDebugJavaWithJavac
:CordovaLib:compileDebugJavaWithJavac - is not incremental (e.g. outputs have changed, no previous execution, etc.).
Note: Some input files use or override a deprecated API.
Note: Recompile with -Xlint:deprecation for details.
:CordovaLib:processDebugJavaRes UP-TO-DATE
:CordovaLib:transformResourcesWithMergeJavaResForDebug
:CordovaLib:transformClassesAndResourcesWithSyncLibJarsForDebug
:CordovaLib:mergeDebugJniLibFolders
:CordovaLib:transformNative_libsWithMergeJniLibsForDebug
:CordovaLib:transformNative_libsWithSyncJniLibsForDebug
:CordovaLib:bundleDebug
:prepareProjectCordovaLibUnspecifiedDebugLibrary
:prepareDebugDependencies
:compileDebugAidl
:compileDebugRenderscript
:generateDebugBuildConfig
:mergeDebugShaders
:compileDebugShaders
:generateDebugAssets
:mergeDebugAssets
:generateDebugResValues
:generateDebugResources
:mergeDebugResources
:processDebugManifest
:processDebugResources
:generateDebugSources
:incrementalDebugJavaCompilationSafeguard
:compileDebugJavaWithJavac
:compileDebugJavaWithJavac - is not incremental (e.g. outputs have changed, no previous execution, etc.).
Note: /project/src/io/sqlc/SQLiteAndroidDatabase.java uses or overrides a deprecated API.
Note: Recompile with -Xlint:deprecation for details.
:compileDebugNdk UP-TO-DATE
:compileDebugSources
:prePackageMarkerForDebug
:transformClassesWithDexForDebug
Merged dex #1 (86 defs/108.5KiB)
Merged dex #2 (17 defs/27.4KiB)
Result is 103 defs/161.1KiB. Took 0.0s
:mergeDebugJniLibFolders
:transformNative_libsWithMergeJniLibsForDebug
:processDebugJavaRes UP-TO-DATE
:transformResourcesWithMergeJavaResForDebug
:validateDebugSigning
:packageDebug
:zipalignDebug
:assembleDebug
:cdvBuildDebug

BUILD SUCCESSFUL

Total time: 2.772 secs
Built the following apk(s): 
	/project/build/outputs/apk/project-debug.apk

**Comment by brodybits** [comment]
Thanks @bakerjay06074 for reporting. This is because the SQLiteAndroidDatabase is designed to work with both old and new AOSP sqlite APIs. I will add a @SuppressWarnings("deprecation") to the SQLiteAndroidDatabase.bindPreHoneycomb method in the Cordova-sqlite-storage and eventually merge it into this version.

**Comment by brodybits** [comment]
Unfortunately I could not figure this out yet. I raised https://github.com/litehelpers/Cordova-sqlite-storage/issues/611 with the **community help** label to investigate and deal with this in the main cordova-sqlite-storage version.
