### ISSUE TITLE
January-March 2017 commercial license giveaway

### ISSUE THREAD

**Issue by brodybits** [litehelpers/Cordova-sqlite-evcore-extbuild-free#17]
@brodybits is happy to announce a commercial license giveaway, under the following terms:
- Single app per company or indie publisher
- Support is available through public forums such as [litehelpers / Cordova-sqlite-evcore-extbuild-free / issues](https://github.com/litehelpers/Cordova-sqlite-evcore-extbuild-free/issues)
- Valid until the end of **March 2017**
- Please have an owner, partner, or other board member provide the following information to <brodybits@litehelpers.net>:
  - Name, description, and location of your company, along with website if available
  - Name and description of app, along with link to any published versions available
  - May we use your app as a sample?
  - How satisfied are you with this plugin and its documentation? Do you have any suggestions for improvement?
  - What kinds of more advanced SQL features such as JOIN, VIEW, or TRIGGER, if any?
  - Major framework used by your app, such as Ionic 1, Ionic 2, React, Node.js, Meteor, etc.?
  - What protocols and frameworks if any does your company use for client-server data synchronization?
  - What are your most difficult challenges related to developing, maintaining, and supporting your software?
  - May @brodybits or other members of @litehelpers contact you with offers or any other updates?

**Comment by brodybits** [comment]
This offer is extended through March 2017.

**Comment by brodybits** [comment]
11 days left!

**Comment by fidelcom1** [comment]
What if I'm only started developing my app and can't provide 'link to any published versions available' ? Thanks.

**Comment by brodybits** [comment]
@fidelcom1 it is OK if your app is not yet ready to be published.

**Comment by brodybits** [comment]
8 days left!

**Comment by brodybits** [comment]
Today is the last day!
