### ISSUE TITLE
[UTF-8] Charset problems [multi-byte UTF-8 characters]

### ISSUE THREAD

**Issue by netmist** [litehelpers/Cordova-sqlite-evcore-extbuild-free#19]
I am facing the problem descrived [here.](https://www.bountysource.com/issues/43129734-sqlite-encoding-problem)
In my device xperia Z5 is working ok but in the emulator (or any Intel processor device) I see the special chars retrieved from sqlite like this ?ffffffc3??ffffffb3? for ó, etc.

As brunocollaco suggests on the above linked thread I think this is a bug with evcore-extbuild-free plugin on intel processors.

Any ideas?

Thank you.

**Comment by mmp-schmitt** [comment]
I recently switched from cordova-sqlite-ext to cordova-sqlite-evcore-extbuild-free. I can confirm the same problem. This problem only occurs with Android, not with iOS.

**Comment by netmist** [comment]
Yes mmp-schmitt this problem occurs with Androids working on a Intel processor device and there are a lot of them.
And also occurs with not-so-special chars ?ffffffe2??ffffff82? is what I got from the € symbol.

**Comment by mmp-schmitt** [comment]
The problem occurs with all UTF-8 characters beyond code 7F. When a character requires 2 bytes or more, the program fails. The Euro character has the URF-8 Hex code: e2 82 ac. 
Obviously there is a character misinterpretation between the x86 C library libsqlc-evcore-native-driver.so and the Java parts.

**Comment by brodybits** [comment]
Possible solution contributed in https://github.com/litehelpers/Android-sqlite-evcore-native-driver-free/pull/2

Planning to publish a similar solution in November 2017.

**Comment by brodybits** [comment]
From <https://github.com/litehelpers/Android-sqlite-evcore-native-driver-free/pull/2#issuecomment-358453518>:
> I just saw the issue in case of 2-octet and 3-octet UTF-8 characters on Android x86_64 emulator, hoping to make this fix in the near future [...]

**Comment by brodybits** [comment]
Some related issues:
- litehelpers/Cordova-sqlite-evcore-extbuild-free#7 - crash in case of emojis and other 4-byte UTF-8 characters
- litehelpers/Cordova-sqlite-evcore-extbuild-free#25 - issue with multi-byte UTF-8 character such as accented characters or Euro symbol in database name
- litehelpers/Cordova-sqlite-evcore-extbuild-free#26 - crash in case of 4-byte UTF-8 character in database file name

I expect to fix this issue in the next major release (related to next major release of cordova-sqlite-storage discussed in litehelpers/Cordova-sqlite-storage#687).

**Comment by brodybits** [comment]
This issue is now resolved ref: <https://github.com/litehelpers/Android-sqlite-evcore-native-driver-free/pull/2#issuecomment-380674108>

**Comment by 21pg** [comment]
Tamil Language (தமிழ்) text was not displaying properly in Android mobile app
