### ISSUE TITLE
Cannot get it to work with Phonegap

### ISSUE THREAD

**Issue by FreddyCrugger** [litehelpers/Cordova-sqlite-evcore-extbuild-free#29]
Hello,

I have installed phonegap, ran the command via the CLI:
npm i cordova-sqlite-evcore-extbuild-free --save

The plugin installed itself in node_modules/cordova-sqlite-evcore-extbuild-free/

I have added the below code to my config.xml
    <plugin name="cordova-sqlite-evcore-extbuild-free" source="npm" spec="~0.9.2" />

But nothing happens when I write a query, did I miss something? It is the first time I use a non "CORE" plugin with Phonegap.

Thank you.

**Comment by brodybits** [comment]
If you use Cordova CLI or PhoneGap CLI you have to use `cordova plugin add` or `phonegap plugin add` to add a plugin.

In case of trouble I suggest you try a simpler plugin such as cordova-plugin-dialogs before you try this one.

**Comment by brodybits** [comment]
Closing due to lack of information. It is recommended to follow the instructions given for Cordova CLI or PhoneGap CLI  and to try a simpler plugin first in case of issues.

In case this is still an issue please give some more information here or in a new issue in Cordova-sqlite-help.
