### ISSUE TITLE
How to test in browser for Android development?

### ISSUE THREAD

**Issue by FreddyCrugger** [litehelpers/Cordova-sqlite-evcore-extbuild-free#31]
Hello,

I am using Phonegap on Windows 10 64 Bit, there is something I just cannot get my head around. If Your plugin does not work in a browser while developing with Phonegap, how do we check our code before generating the APK? I have added my code but simply cannot test it....

Thank you.

**Comment by brodybits** [comment]
Cordova provides tooling to build and run your application on Android emulator, Android device, iOS emulator, iOS device, etc. etc., with plenty of documentation out there.

For this kind of question please research more carefully then ask in very specific terms in cordova-sqlite-help.
