### ISSUE TITLE
The size of the pre-populated external sqlite database

### ISSUE THREAD

**Issue by 543802360** [litehelpers/Cordova-sqlite-evcore-extbuild-free#41]
hello, I have Encountered a big problem，is the size of the pre-populated external sqlite database important? now, when the db size is 10MB, it's ok to open it ; but when the db size is 100MB, it's failed to open it.My app may need the db size several GB, so what can I do for this? Hope for your help, thank you

**Comment by brodybits** [comment]
A reproduction demo would be extremely helpful, <https://github.com/brodybits/cordova-sqlite-ext-bootstrap-starter-app> is the recommended starting point.

Marked as an enhancement for testing at some point in the future. Priority goes to paid customers, please contact <sales@litehelpers.net> for more information.

**Comment by 543802360** [comment]
Thank you for your reply.now I can open a 1.7GB mbtiles file
